<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationTitle>CS2 Long Jump &amp; Sync Lab</ApplicationTitle>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <RootNamespace>LJTrainer</RootNamespace>
    <Version>1.1.5</Version>
    <AssemblyVersion>1.1.5.0</AssemblyVersion>
    <FileVersion>1.1.5.0</FileVersion>
    <InformationalVersion>v1.1.5</InformationalVersion>
  </PropertyGroup>


  <ItemGroup>
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
    <PackageReference Include="Svg.Skia" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>


</Project>
